### PR TITLE
fix(functions): allow ref to correctly handle CommaDelimitedList

### PR DESCRIPTION
**Pull request by dhutchison**
Leaving this as a draft just now as I've just twigged there are other `List<foo>` parameter types which will have the same issue. Will pick up that tomorrow.

### CODE REVIEW

**Comment by dhutchison** [comment]
@shadycuz looks like the license compliance check has got stuck again - do you know why? 

Could you review / merge / release this? Thanks.

**Comment by jamesmcminn96** [comment]
Hey @shadycuz & @dhutchison, thanks heaps for the work on this so far. Wondering if it'd be possible for a new release with this fix to be cut soon?

**Comment by shadycuz** [comment]
> Hey @shadycuz & @dhutchison, thanks heaps for the work on this so far. Wondering if it'd be possible for a new release with this fix to be cut soon?

Yes, this is my fault. I will take care of shortly.

**Comment by jamesmcminn96** [comment]
Thank you so much!

**Pull request merged**
